# Podinfo Deployment Configuration
# Generated by setup-config.sh

environment = "dev"
github_org = "CLEMENTJOHNSHAJI"
github_repo = "podinfo-deployment-system"
github_branch = "main"
aws_region = "us-west-2"
aws_account_id = "484826611466"
